name: Build android/ios

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - ".github/workflows/build.yml"
      - "!**.md"
      - "!**.gitignore"

  pull_request:
    branches: [master]
    paths:
      - "app/**"
      - ".github/workflows/build.yml"
      - "!**.md"
      - "!**.gitignore"

  workflow_dispatch:

jobs:
  ios-build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.2"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Podfile
        run: |
          cd app
          cd ios
          rm Podfile.lock
          flutter clean
          flutter pub get
          pod install
          pod update
          cd ..
      - name: Build
        run: |
          cd app
          flutter build ios --release --no-codesign
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip Payload.ipa
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: ipa-build
          path: app/Payload.ipa

  android-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.2"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Build
        run: |
          cd app
          flutter clean
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: ./app/build/app/outputs/apk/release/app-release.apk
