name: Crawl CourtAuction

on:
  workflow_dispatch:

jobs:
  crawling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: |
          cd crawler
          npm install
      - name: Run
        run: |
          cd crawler
          node courtauction.js
          node courtauction-runparam.js > a.txt
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: crawling-result
          path: crawler/a.txt
